# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_brinco', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
                ('especificacoes', models.TextField(blank=True, null=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.Fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='GestorFazenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.Fazenda')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
