# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0002_fazenda_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('data_pesagem', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gado',
            name='peso',
        ),
        migrations.AddField(
            model_name='pesagem',
            name='gado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.Gado'),
        ),
    ]
