# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0003_auto_20180120_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='access_token',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
